const EVENT_TYPES = {
  // Container Events
  CONTAINER_CREATED: 'CONTAINER_CREATED',
  LOADED_ON_SHIP: 'LOADED_ON_SHIP',
  MOVED: 'MOVED',
  ARRIVED_AT_PORT: 'ARRIVED_AT_PORT',
  TEMPERATURE_SPIKE: 'TEMPERATURE_SPIKE',
  CONTAINER_DAMAGED: 'CONTAINER_DAMAGED',
  CONTAINER_INSPECTED: 'CONTAINER_INSPECTED',
  CONTAINER_DELAYED: 'CONTAINER_DELAYED',

  // Inventory Events
  INVENTORY_ADDED: 'INVENTORY_ADDED',
  INVENTORY_REMOVED: 'INVENTORY_REMOVED',
  INVENTORY_UPDATED: 'INVENTORY_UPDATED',
  INVENTORY_ADJUSTED: 'INVENTORY_ADJUSTED',
  STOCK_ALERT: 'STOCK_ALERT',

  // Financial Events
  TRANSACTION_CREATED: 'TRANSACTION_CREATED',
  TRANSACTION_COMPLETED: 'TRANSACTION_COMPLETED',
  TRANSACTION_FAILED: 'TRANSACTION_FAILED',
  PAYMENT_RECEIVED: 'PAYMENT_RECEIVED',
  PAYMENT_SENT: 'PAYMENT_SENT',

  // Sensor Events
  SENSOR_READING: 'SENSOR_READING',
  SENSOR_ALERT: 'SENSOR_ALERT',
  SENSOR_CALIBRATED: 'SENSOR_CALIBRATED',

  // System Events
  SYSTEM_STARTED: 'SYSTEM_STARTED',
  SYSTEM_ERROR: 'SYSTEM_ERROR',
  SYSTEM_MAINTENANCE: 'SYSTEM_MAINTENANCE'
};

const EVENT_CATEGORIES = {
  CONTAINER: 'Container',
  INVENTORY: 'Inventory',
  FINANCIAL: 'Financial',
  SENSOR: 'Sensor',
  SYSTEM: 'System'
};

const EVENT_CATEGORY_MAP = {
  [EVENT_TYPES.CONTAINER_CREATED]: EVENT_CATEGORIES.CONTAINER,
  [EVENT_TYPES.LOADED_ON_SHIP]: EVENT_CATEGORIES.CONTAINER,
  [EVENT_TYPES.MOVED]: EVENT_CATEGORIES.CONTAINER,
  [EVENT_TYPES.ARRIVED_AT_PORT]: EVENT_CATEGORIES.CONTAINER,
  [EVENT_TYPES.TEMPERATURE_SPIKE]: EVENT_CATEGORIES.CONTAINER,
  [EVENT_TYPES.CONTAINER_DAMAGED]: EVENT_CATEGORIES.CONTAINER,
  [EVENT_TYPES.CONTAINER_INSPECTED]: EVENT_CATEGORIES.CONTAINER,
  [EVENT_TYPES.CONTAINER_DELAYED]: EVENT_CATEGORIES.CONTAINER,
  [EVENT_TYPES.INVENTORY_ADDED]: EVENT_CATEGORIES.INVENTORY,
  [EVENT_TYPES.INVENTORY_REMOVED]: EVENT_CATEGORIES.INVENTORY,
  [EVENT_TYPES.INVENTORY_UPDATED]: EVENT_CATEGORIES.INVENTORY,
  [EVENT_TYPES.INVENTORY_ADJUSTED]: EVENT_CATEGORIES.INVENTORY,
  [EVENT_TYPES.STOCK_ALERT]: EVENT_CATEGORIES.INVENTORY,
  [EVENT_TYPES.TRANSACTION_CREATED]: EVENT_CATEGORIES.FINANCIAL,
  [EVENT_TYPES.TRANSACTION_COMPLETED]: EVENT_CATEGORIES.FINANCIAL,
  [EVENT_TYPES.TRANSACTION_FAILED]: EVENT_CATEGORIES.FINANCIAL,
  [EVENT_TYPES.PAYMENT_RECEIVED]: EVENT_CATEGORIES.FINANCIAL,
  [EVENT_TYPES.PAYMENT_SENT]: EVENT_CATEGORIES.FINANCIAL,
  [EVENT_TYPES.SENSOR_READING]: EVENT_CATEGORIES.SENSOR,
  [EVENT_TYPES.SENSOR_ALERT]: EVENT_CATEGORIES.SENSOR,
  [EVENT_TYPES.SENSOR_CALIBRATED]: EVENT_CATEGORIES.SENSOR,
  [EVENT_TYPES.SYSTEM_STARTED]: EVENT_CATEGORIES.SYSTEM,
  [EVENT_TYPES.SYSTEM_ERROR]: EVENT_CATEGORIES.SYSTEM,
  [EVENT_TYPES.SYSTEM_MAINTENANCE]: EVENT_CATEGORIES.SYSTEM
};

const EVENT_SEVERITY = {
  [EVENT_TYPES.CONTAINER_CREATED]: 'info',
  [EVENT_TYPES.LOADED_ON_SHIP]: 'info',
  [EVENT_TYPES.MOVED]: 'info',
  [EVENT_TYPES.ARRIVED_AT_PORT]: 'info',
  [EVENT_TYPES.TEMPERATURE_SPIKE]: 'warning',
  [EVENT_TYPES.CONTAINER_DAMAGED]: 'critical',
  [EVENT_TYPES.CONTAINER_INSPECTED]: 'info',
  [EVENT_TYPES.CONTAINER_DELAYED]: 'warning',
  [EVENT_TYPES.INVENTORY_ADDED]: 'info',
  [EVENT_TYPES.INVENTORY_REMOVED]: 'info',
  [EVENT_TYPES.INVENTORY_UPDATED]: 'info',
  [EVENT_TYPES.INVENTORY_ADJUSTED]: 'warning',
  [EVENT_TYPES.STOCK_ALERT]: 'critical',
  [EVENT_TYPES.TRANSACTION_CREATED]: 'info',
  [EVENT_TYPES.TRANSACTION_COMPLETED]: 'info',
  [EVENT_TYPES.TRANSACTION_FAILED]: 'error',
  [EVENT_TYPES.PAYMENT_RECEIVED]: 'info',
  [EVENT_TYPES.PAYMENT_SENT]: 'info',
  [EVENT_TYPES.SENSOR_READING]: 'debug',
  [EVENT_TYPES.SENSOR_ALERT]: 'warning',
  [EVENT_TYPES.SENSOR_CALIBRATED]: 'info',
  [EVENT_TYPES.SYSTEM_STARTED]: 'info',
  [EVENT_TYPES.SYSTEM_ERROR]: 'error',
  [EVENT_TYPES.SYSTEM_MAINTENANCE]: 'warning'
};

const getEventCategory = (eventType) => {
  return EVENT_CATEGORY_MAP[eventType] || 'Unknown';
};

const getEventSeverity = (eventType) => {
  return EVENT_SEVERITY[eventType] || 'info';
};

const isValidEventType = (eventType) => {
  return Object.values(EVENT_TYPES).includes(eventType);
};

const getEventTypesByCategory = (category) => {
  return Object.entries(EVENT_CATEGORY_MAP)
    .filter(([, cat]) => cat === category)
    .map(([type]) => type);
};

module.exports = {
  EVENT_TYPES,
  EVENT_CATEGORIES,
  EVENT_CATEGORY_MAP,
  EVENT_SEVERITY,
  getEventCategory,
  getEventSeverity,
  isValidEventType,
  getEventTypesByCategory
};
